dist: trusty
language: generic

before_install:
  - openssl aes-256-cbc -K $encrypted_f4bf9b6bfcf8_key -iv $encrypted_f4bf9b6bfcf8_iv -in id_rsa_travis_herrmann_in_gh_pages.enc -out id_rsa_travis_herrmann_in_gh_pages -d
  - chmod 600 id_rsa_travis_herrmann_in_gh_pages
  - eval `ssh-agent -s`
  - ssh-add id_rsa_travis_herrmann_in_gh_pages
  - git config user.name "davherrmann"
  - git config user.email "davherrmann@googlemail.com"

script:
  - git clone git@github.com:davherrmann/herrmanns.in build --branch master --single-branch
  - cd build
  - git clone git@gist.github.com:${HERRMANNS_IN_BIRMINGHAM_GIST} messages --branch master --single-branch
  - touch index.html
  - echo "hello world!" >> index.html

after_success:
  - git add --all .
  - git commit -m "rebuild website triggered by commit ${TRAVIS_COMMIT}"
  - git push origin master
